[package]
name = "advent_of_code_2025"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2"
rand = "0.8.5"
reqwest = { version = "0.11", features = ["blocking","cookies"] }
rayon = "1.10.0"